name = "familyrealtime"
main = "src/worker.js"
workers_dev = true
compatibility_date = "2025-06-21"

[durable_objects]
bindings = [
  { name = "CHAT_ROOM", class_name = "ChatRoom" } # This is the crucial Durable Object binding
]
